name: wave
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/fonts/ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/ubuntu/Ubuntu-LightItalic.ttf
          style: italic
          weight: 300

  assets:
    - assets/images/logo.png
