name: Verify Pull Request
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3.1.2
      - uses: britannio/action-install-flutter@v1.1
      - name: Install Python Packages
        working-directory: ./server
        run: pip install -r requirements.txt
      - name: Install Flutter Packages
        working-directory: ./client
        run: dart pub get
